version: '3.8'
services:
  genshinchat-front:
    container_name: genshinchat-front
    restart: always
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - "80:80"
    